name: Release Drafter
on:
  push:
    branches:
      - v4
    paths-ignore:
      - package.json
jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
